"""Markdown report generation for research results."""

import os
from collections import defaultdict
from datetime import datetime
from typing import Optional
from .models import ResearchReport
from .config import config

SOURCE_LABELS = {
    "arxiv": "Academic Papers (arXiv)",
    "openalex": "Academic Papers (OpenAlex)",
    "dblp": "Computer Science Bibliography (DBLP)",
    "europepmc": "Biomedical & Life Sciences (Europe PMC)",
    "core": "Open Access Research (CORE)",
    "crossref": "DOI Metadata Registry (CrossRef)",
    "semantic_scholar": "Academic Papers (Semantic Scholar)",
    "web": "Web Results",
    "news": "News Articles",
    "hackernews": "Community Discussions (HackerNews)",
}


def generate_markdown(report: ResearchReport) -> str:
    """
    Generate a formatted Markdown report from research results.

    Args:
        report: ResearchReport object containing all research data

    Returns:
        Formatted Markdown string
    """
    # Format timestamp
    timestamp = report.generated_at.strftime("%Y-%m-%d %H:%M:%S")

    # Build markdown sections
    md_parts = []

    # Header
    md_parts.append(f"# Deep Research Report: {report.query.topic}")
    md_parts.append(f"\n*Generated: {timestamp}*\n")
    md_parts.append("---\n")

    # Query information
    md_parts.append("## Research Query")
    md_parts.append(f"- **Topic**: {report.query.topic}")
    md_parts.append(
        f"- **Date Range**: {report.query.date_from or 'Not specified'} to {report.query.date_to or 'Not specified'}"
    )
    md_parts.append(f"- **Max Results**: {report.query.max_results}")
    md_parts.append(f"- **Results Found**: {len(report.results)}\n")
    md_parts.append("---\n")

    # Executive Summary
    md_parts.append("## Executive Summary")
    md_parts.append(f"\n{report.summary}\n")
    md_parts.append("---\n")

    # Key Insights
    if report.insights:
        md_parts.append("## Key Insights\n")
        for idx, insight in enumerate(report.insights, 1):
            md_parts.append(f"{idx}. {insight}")
        md_parts.append("\n---\n")

    # Group results by source
    if report.results:
        grouped: dict[str, list] = defaultdict(list)
        for result in report.results:
            grouped[result.source].append(result)

        for source_key, group_results in grouped.items():
            section_label = SOURCE_LABELS.get(source_key, source_key.title())
            md_parts.append(f"## {section_label} ({len(group_results)} found)\n")

            for idx, result in enumerate(group_results, 1):
                md_parts.append(f"### {idx}. {result.title}\n")

                # Authors
                if result.authors:
                    authors_str = ", ".join(result.authors[:5])
                    if len(result.authors) > 5:
                        authors_str += " et al."
                    md_parts.append(f"**Authors**: {authors_str}  ")

                # Metadata
                if result.published_date:
                    md_parts.append(f"**Published**: {result.published_date}  ")
                md_parts.append(f"**Source**: {result.source}  ")
                if result.url:
                    md_parts.append(f"**URL**: [{result.url}]({result.url})  \n")

                # Abstract
                if result.abstract:
                    md_parts.append("**Abstract**:")
                    md_parts.append(f"\n{result.abstract}\n")

    # Footer
    md_parts.append("---\n")
    md_parts.append(
        f"*This report was generated by the Deep Research Automation Tool using Ollama ({config.ollama_model})*"
    )

    return "\n".join(md_parts)


def save_report(content: str, filename: Optional[str] = None) -> str:
    """
    Save the markdown report to a file.

    Args:
        content: Markdown content to save
        filename: Optional custom filename (defaults to timestamped name)

    Returns:
        Path to the saved file

    Raises:
        Exception: If file writing fails
    """
    try:
        # Create output directory if it doesn't exist
        output_dir = config.output_dir
        os.makedirs(output_dir, exist_ok=True)

        # Generate filename if not provided
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"research_report_{timestamp}.md"

        # Full path
        filepath = os.path.join(output_dir, filename)

        # Write file
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        return filepath

    except Exception as e:
        raise Exception(f"Failed to save report: {str(e)}")
